//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPM2.Models
{
    using System;
    using System.Collections.Generic;

    public partial class ReadingHistory
    {
        public int HistoryID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> ChapterID { get; set; }  // Thêm thuộc tính ChapterID
        public Nullable<System.DateTime> LastReadDate { get; set; }

        // Khóa ngoại liên kết với bảng UpdateChapter
        public virtual UpdateChapter UpdateChapter { get; set; } // Thêm mối quan hệ với bảng UpdateChapter
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }

    public class HistoryViewModel
    {
        public List<Product> Products { get; set; }
        public List<Category> Categories { get; set; }
        public Product Product { get; set; }
        public Category Category { get; set; } // Đảm bảo Category không null khi sử dụng
        public int CurrentPage { get; set; }
        public int TotalPages { get; set; }
    }
}
